version: "3.9"

services:
  calculator-api-staging:
    image: lab4/calculator:dev
    container_name: calculator-api-staging
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8081:8080"
    restart: unless-stopped
